/*
 * This source file was generated by the Gradle 'init' task
 */
package javaroke;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    String output = "Hello, World!";
    assertEquals("The greeting should be 'Hello, World!'", "Hello, World!", output);
  }

  @Test
  public void mainMethodRunsWithoutExceptions() {
    try {
      Main.main(new String[] {});
    } catch (Exception e) {
      fail("Main method should run without throwing exceptions");
    }
  }
}
